services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: jdb-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "${MSSQL_PID}"
    ports:
      - "1433:1433"
    volumes:
      - jdb_sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -Q \"SELECT 1\" -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  jdb_sql_data:
